//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentForm.StudentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        StudentForm.StudentService.HelloWorldResponse HelloWorld(StudentForm.StudentService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetListStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListStudents", ReplyAction="*")]
        StudentForm.StudentService.GetListStudentsResponse GetListStudents(StudentForm.StudentService.GetListStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name studentEx from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveStudent", ReplyAction="*")]
        StudentForm.StudentService.SaveStudentResponse SaveStudent(StudentForm.StudentService.SaveStudentRequest request);
        
        // CODEGEN: Generating message contract since element name ShowStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowStudent", ReplyAction="*")]
        StudentForm.StudentService.ShowStudentResponse ShowStudent(StudentForm.StudentService.ShowStudentRequest request);
        
        // CODEGEN: Generating message contract since element name studentExSearch from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStudent", ReplyAction="*")]
        StudentForm.StudentService.SearchStudentResponse SearchStudent(StudentForm.StudentService.SearchStudentRequest request);
        
        // CODEGEN: Generating message contract since element name studentExUpdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStudent", ReplyAction="*")]
        StudentForm.StudentService.UpdateStudentResponse UpdateStudent(StudentForm.StudentService.UpdateStudentRequest request);
        
        // CODEGEN: Generating message contract since element name studentExDelete from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteStudent", ReplyAction="*")]
        StudentForm.StudentService.DeleteStudentResponse DeleteStudent(StudentForm.StudentService.DeleteStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(StudentForm.StudentService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(StudentForm.StudentService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStudents", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.GetListStudentsRequestBody Body;
        
        public GetListStudentsRequest() {
        }
        
        public GetListStudentsRequest(StudentForm.StudentService.GetListStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListStudentsRequestBody {
        
        public GetListStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.GetListStudentsResponseBody Body;
        
        public GetListStudentsResponse() {
        }
        
        public GetListStudentsResponse(StudentForm.StudentService.GetListStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student[] GetListStudentsResult;
        
        public GetListStudentsResponseBody() {
        }
        
        public GetListStudentsResponseBody(StudentForm.StudentService.Student[] GetListStudentsResult) {
            this.GetListStudentsResult = GetListStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudent", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.SaveStudentRequestBody Body;
        
        public SaveStudentRequest() {
        }
        
        public SaveStudentRequest(StudentForm.StudentService.SaveStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student studentEx;
        
        public SaveStudentRequestBody() {
        }
        
        public SaveStudentRequestBody(StudentForm.StudentService.Student studentEx) {
            this.studentEx = studentEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.SaveStudentResponseBody Body;
        
        public SaveStudentResponse() {
        }
        
        public SaveStudentResponse(StudentForm.StudentService.SaveStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveStudentResponseBody {
        
        public SaveStudentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowStudent", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.ShowStudentRequestBody Body;
        
        public ShowStudentRequest() {
        }
        
        public ShowStudentRequest(StudentForm.StudentService.ShowStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowStudentRequestBody {
        
        public ShowStudentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.ShowStudentResponseBody Body;
        
        public ShowStudentResponse() {
        }
        
        public ShowStudentResponse(StudentForm.StudentService.ShowStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student[] ShowStudentResult;
        
        public ShowStudentResponseBody() {
        }
        
        public ShowStudentResponseBody(StudentForm.StudentService.Student[] ShowStudentResult) {
            this.ShowStudentResult = ShowStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudent", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.SearchStudentRequestBody Body;
        
        public SearchStudentRequest() {
        }
        
        public SearchStudentRequest(StudentForm.StudentService.SearchStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student studentExSearch;
        
        public SearchStudentRequestBody() {
        }
        
        public SearchStudentRequestBody(StudentForm.StudentService.Student studentExSearch) {
            this.studentExSearch = studentExSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.SearchStudentResponseBody Body;
        
        public SearchStudentResponse() {
        }
        
        public SearchStudentResponse(StudentForm.StudentService.SearchStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student[] SearchStudentResult;
        
        public SearchStudentResponseBody() {
        }
        
        public SearchStudentResponseBody(StudentForm.StudentService.Student[] SearchStudentResult) {
            this.SearchStudentResult = SearchStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudent", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.UpdateStudentRequestBody Body;
        
        public UpdateStudentRequest() {
        }
        
        public UpdateStudentRequest(StudentForm.StudentService.UpdateStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student studentExUpdate;
        
        public UpdateStudentRequestBody() {
        }
        
        public UpdateStudentRequestBody(StudentForm.StudentService.Student studentExUpdate) {
            this.studentExUpdate = studentExUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.UpdateStudentResponseBody Body;
        
        public UpdateStudentResponse() {
        }
        
        public UpdateStudentResponse(StudentForm.StudentService.UpdateStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStudentResponseBody {
        
        public UpdateStudentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudent", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.DeleteStudentRequestBody Body;
        
        public DeleteStudentRequest() {
        }
        
        public DeleteStudentRequest(StudentForm.StudentService.DeleteStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentForm.StudentService.Student studentExDelete;
        
        public DeleteStudentRequestBody() {
        }
        
        public DeleteStudentRequestBody(StudentForm.StudentService.Student studentExDelete) {
            this.studentExDelete = studentExDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentForm.StudentService.DeleteStudentResponseBody Body;
        
        public DeleteStudentResponse() {
        }
        
        public DeleteStudentResponse(StudentForm.StudentService.DeleteStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteStudentResponseBody {
        
        public DeleteStudentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : StudentForm.StudentService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<StudentForm.StudentService.ServiceSoap>, StudentForm.StudentService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.HelloWorldResponse StudentForm.StudentService.ServiceSoap.HelloWorld(StudentForm.StudentService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            StudentForm.StudentService.HelloWorldRequest inValue = new StudentForm.StudentService.HelloWorldRequest();
            inValue.Body = new StudentForm.StudentService.HelloWorldRequestBody();
            StudentForm.StudentService.HelloWorldResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.GetListStudentsResponse StudentForm.StudentService.ServiceSoap.GetListStudents(StudentForm.StudentService.GetListStudentsRequest request) {
            return base.Channel.GetListStudents(request);
        }
        
        public StudentForm.StudentService.Student[] GetListStudents() {
            StudentForm.StudentService.GetListStudentsRequest inValue = new StudentForm.StudentService.GetListStudentsRequest();
            inValue.Body = new StudentForm.StudentService.GetListStudentsRequestBody();
            StudentForm.StudentService.GetListStudentsResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).GetListStudents(inValue);
            return retVal.Body.GetListStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.SaveStudentResponse StudentForm.StudentService.ServiceSoap.SaveStudent(StudentForm.StudentService.SaveStudentRequest request) {
            return base.Channel.SaveStudent(request);
        }
        
        public void SaveStudent(StudentForm.StudentService.Student studentEx) {
            StudentForm.StudentService.SaveStudentRequest inValue = new StudentForm.StudentService.SaveStudentRequest();
            inValue.Body = new StudentForm.StudentService.SaveStudentRequestBody();
            inValue.Body.studentEx = studentEx;
            StudentForm.StudentService.SaveStudentResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).SaveStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.ShowStudentResponse StudentForm.StudentService.ServiceSoap.ShowStudent(StudentForm.StudentService.ShowStudentRequest request) {
            return base.Channel.ShowStudent(request);
        }
        
        public StudentForm.StudentService.Student[] ShowStudent() {
            StudentForm.StudentService.ShowStudentRequest inValue = new StudentForm.StudentService.ShowStudentRequest();
            inValue.Body = new StudentForm.StudentService.ShowStudentRequestBody();
            StudentForm.StudentService.ShowStudentResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).ShowStudent(inValue);
            return retVal.Body.ShowStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.SearchStudentResponse StudentForm.StudentService.ServiceSoap.SearchStudent(StudentForm.StudentService.SearchStudentRequest request) {
            return base.Channel.SearchStudent(request);
        }
        
        public StudentForm.StudentService.Student[] SearchStudent(StudentForm.StudentService.Student studentExSearch) {
            StudentForm.StudentService.SearchStudentRequest inValue = new StudentForm.StudentService.SearchStudentRequest();
            inValue.Body = new StudentForm.StudentService.SearchStudentRequestBody();
            inValue.Body.studentExSearch = studentExSearch;
            StudentForm.StudentService.SearchStudentResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).SearchStudent(inValue);
            return retVal.Body.SearchStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.UpdateStudentResponse StudentForm.StudentService.ServiceSoap.UpdateStudent(StudentForm.StudentService.UpdateStudentRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public void UpdateStudent(StudentForm.StudentService.Student studentExUpdate) {
            StudentForm.StudentService.UpdateStudentRequest inValue = new StudentForm.StudentService.UpdateStudentRequest();
            inValue.Body = new StudentForm.StudentService.UpdateStudentRequestBody();
            inValue.Body.studentExUpdate = studentExUpdate;
            StudentForm.StudentService.UpdateStudentResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).UpdateStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentForm.StudentService.DeleteStudentResponse StudentForm.StudentService.ServiceSoap.DeleteStudent(StudentForm.StudentService.DeleteStudentRequest request) {
            return base.Channel.DeleteStudent(request);
        }
        
        public void DeleteStudent(StudentForm.StudentService.Student studentExDelete) {
            StudentForm.StudentService.DeleteStudentRequest inValue = new StudentForm.StudentService.DeleteStudentRequest();
            inValue.Body = new StudentForm.StudentService.DeleteStudentRequestBody();
            inValue.Body.studentExDelete = studentExDelete;
            StudentForm.StudentService.DeleteStudentResponse retVal = ((StudentForm.StudentService.ServiceSoap)(this)).DeleteStudent(inValue);
        }
    }
}
